### ISSUE TITLE
Partenaire Generation

### ISSUE THREAD

**Issue by emilieguth** [bayesimpact/ma-voie#635]
Pas de lien vers la formation Generation Developer FullStack : 
elle est non cliquable (voir capture en PJ) : 
> il n'y a donc personne qui puisse cliquer sur cette formation

![Capture d’écran 2021-04-07 à 11.09.01.png](https://zube.io/files/bayesimpact/44cb0b5c019814c015502ee0bc0bd96e-capture-decran-2021-04-07-a-11-09-01.png)

**Comment by pcorpet** [comment]
This training was created manually? A partnerId field was missing in the config. This should now be fixed.
