### ISSUE TITLE
Open classrooms partner

### ISSUE THREAD

**Issue by emilieguth** [bayesimpact/ma-voie#637]
Le programme OpenClassrooms Développez votre réseau professionnel : 
a) le bouton découvrir est mangé par le texte (PJ)
b) le lien ne renvoie renvoie pas là où il devrait - je te forward également le mail qu'openclassroom nous avait envoyé
=> should be https://openclassrooms.com/fr/courses/5754261-developpez-votre-reseau-professionnel?utm_source=partners&utm_medium=referral&utm_campaign=referrer_partners_fr_fr_oth_prospecting_mavoie_210202_00

![Capture d’écran 2021-04-07 à 11.24.43.png](https://zube.io/files/bayesimpact/51fc71f800bc165d98aa969736b2db67-capture-decran-2021-04-07-a-11-24-43.png)

**Comment by pcorpet** [comment]
Link fixed in prod
